akka {
  actor {

  }
}

akka-kryo-serialization {
  type = "graph"
  id-strategy = "incremental"
  serialize-lambdas = true
  # Required to handle Scala closure capture safely
  kryo-initializer = "io.altoo.akka.serialization.kryo.DefaultKryoInitializer"
}